import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/**jelly hook tracker */}
        <script src="http://localhost:3000/tracker.js" data-key="6b18ad00-fc59-4841-bfbe-8fff33c7a998"></script>
      <script src="http://localhost:3000/tracker.js" data-key="d9bc5f3a-a68c-4ae7-a079-a8d5ca839a4b"></script>
      </body>
    </html>
  );
}
